import { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart3, House, LayoutDashboard, LogOut, ScanLine } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";

import { getReportById, getReports, getStats, predict } from "../api";
import HistoryTable from "../components/HistoryTable";
import Navbar from "../components/Navbar";
import ResultCard from "../components/ResultCard";
import StageChart from "../components/StageChart";
import UploadCard from "../components/UploadCard";


const emptyStats = {
  total_scans: 0,
  stage_counts: {
    Normal: 0,
    Mild: 0,
    Severe: 0,
  },
  accuracy_avg: 0,
  recent_scans: [],
};


const mapReportToResult = (report) => {
  const isDemoMode = String(report.advice || "").includes("Fallback demo analysis was used");

  return {
    report_id: report.id,
    stage: report.stage,
    confidence: Number(report.confidence),
    probabilities: {
      Normal: Number(report.normal_prob),
      Mild: Number(report.mild_prob),
      Severe: Number(report.severe_prob),
    },
    advice: report.advice,
    created_at: report.created_at,
    image_filename: report.image_filename,
    source: "history",
    analysis_mode: isDemoMode ? "heuristic_demo" : "trained_model",
    model_message: isDemoMode
      ? "Demo mode is active. Run `python model/train.py` in the backend folder to switch to the trained CNN model."
      : "Prediction generated by the trained CNN model.",
  };
};


function Dashboard({ authUser, isDarkMode, onToggleTheme, onLogout }) {
  const navigate = useNavigate();
  const [reports, setReports] = useState([]);
  const [stats, setStats] = useState(emptyStats);
  const [currentResult, setCurrentResult] = useState(null);
  const [loadingDashboard, setLoadingDashboard] = useState(true);
  const [analyzing, setAnalyzing] = useState(false);
  const [activeViewId, setActiveViewId] = useState(null);
  const [uploadResetKey, setUploadResetKey] = useState(0);
  const [activeNav, setActiveNav] = useState("new-scan");

  const scrollToSection = (sectionId) => {
    const section = document.getElementById(sectionId);

    if (section) {
      section.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  const handleLogout = useCallback(() => {
    onLogout();
    navigate("/login");
  }, [navigate, onLogout]);

  const refreshDashboardData = useCallback(
    async (showSpinner = false) => {
      if (showSpinner) {
        setLoadingDashboard(true);
      }

      try {
        const [reportsResponse, statsResponse] = await Promise.all([getReports(), getStats()]);
        setReports(reportsResponse);
        setStats(statsResponse);
      } catch (error) {
        if (error.response?.status === 401) {
          toast.error("Your session expired. Please log in again.");
          handleLogout();
          return;
        }

        toast.error(error.response?.data?.error || "Unable to load dashboard data.");
      } finally {
        if (showSpinner) {
          setLoadingDashboard(false);
        }
      }
    },
    [handleLogout],
  );

  useEffect(() => {
    refreshDashboardData(true);
  }, [refreshDashboardData]);

  const handleAnalyze = async ({ file, previewUrl, source }) => {
    const formData = new FormData();
    formData.append("image", file);
    setAnalyzing(true);

    try {
      const prediction = await predict(formData);
      setCurrentResult({
        ...prediction,
        previewUrl,
        source,
      });
      setActiveNav("result-section");
      toast.success(
        prediction.analysis_mode === "heuristic_demo"
          ? "Demo analysis complete. Train the model to switch to CNN screening."
          : "Analysis complete. Result saved to history.",
      );
      await refreshDashboardData();
      scrollToSection("result-section");
    } catch (error) {
      toast.error(
        error.response?.data?.error ||
          "Prediction failed. Make sure the model has been trained and the backend is running.",
      );
    } finally {
      setAnalyzing(false);
    }
  };

  const handleViewReport = async (reportId) => {
    setActiveViewId(reportId);

    try {
      const report = await getReportById(reportId);
      setCurrentResult(mapReportToResult(report));
      setActiveNav("result-section");
      scrollToSection("result-section");
      toast.success(`Loaded report #${reportId}.`);
    } catch (error) {
      toast.error(error.response?.data?.error || "Could not load that report.");
    } finally {
      setActiveViewId(null);
    }
  };

  const handleSaveReport = () => {
    if (!currentResult?.report_id) {
      return;
    }

    setActiveNav("history-section");
    toast.success("Report is already stored in history.");
    scrollToSection("history-section");
  };

  const handleScanAgain = () => {
    setCurrentResult(null);
    setUploadResetKey((value) => value + 1);
    setActiveNav("new-scan");
    scrollToSection("new-scan");
  };

  const quickStats = useMemo(
    () => [
      {
        label: "Total scans",
        value: Number(stats.total_scans || 0),
      },
      {
        label: "Average confidence",
        value: `${Number(stats.accuracy_avg || 0).toFixed(1)}%`,
      },
      {
        label: "Latest stage",
        value: currentResult?.stage || stats.recent_scans?.[0]?.stage || "Waiting",
      },
    ],
    [currentResult?.stage, stats.accuracy_avg, stats.recent_scans, stats.total_scans],
  );

  const navigationItems = [
    {
      type: "route",
      label: "Home",
      icon: House,
      to: "/",
    },
    {
      type: "anchor",
      label: "New Scan",
      icon: ScanLine,
      id: "new-scan",
    },
    {
      type: "anchor",
      label: "History",
      icon: LayoutDashboard,
      id: "history-section",
    },
    {
      type: "anchor",
      label: "Stats",
      icon: BarChart3,
      id: "stats-section",
    },
  ];

  return (
    <main className="min-h-screen px-4 py-5 md:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl lg:hidden">
        <Navbar
          authUser={authUser}
          isDarkMode={isDarkMode}
          onToggleTheme={onToggleTheme}
          onLogout={handleLogout}
          compact
        />
      </div>

      <div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[280px_minmax(0,1fr)]">
        <aside className="sticky top-5 hidden h-[calc(100vh-40px)] lg:block">
          <div className="glass-card flex h-full flex-col justify-between p-5">
            <div>
              <div className="mb-8 flex items-center gap-3">
                <div className="grid h-12 w-12 place-items-center rounded-2xl bg-brand text-white shadow-lg shadow-brand/20">
                  <ScanLine className="h-5 w-5" />
                </div>
                <div>
                  <p className="font-display text-lg font-bold text-slate-900 dark:text-white">
                    Cataract AI
                  </p>
                  <p className="text-sm text-slate-500 dark:text-slate-400">
                    Screening dashboard
                  </p>
                </div>
              </div>

              <div className="rounded-[24px] bg-slate-50/90 p-4 dark:bg-slate-950/70">
                <p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">
                  Signed in as
                </p>
                <p className="mt-2 font-semibold text-slate-900 dark:text-white">
                  {authUser?.name || "User"}
                </p>
                <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
                  {authUser?.email || "No email available"}
                </p>
              </div>

              <nav className="mt-8 grid gap-2">
                {navigationItems.map((item) =>
                  item.type === "route" ? (
                    <Link key={item.label} to={item.to} className="sidebar-link">
                      <item.icon className="h-4 w-4" />
                      {item.label}
                    </Link>
                  ) : (
                    <button
                      key={item.id}
                      type="button"
                      onClick={() => {
                        setActiveNav(item.id);
                        scrollToSection(item.id);
                      }}
                      className={`sidebar-link ${activeNav === item.id ? "active" : ""}`}
                    >
                      <item.icon className="h-4 w-4" />
                      {item.label}
                    </button>
                  ),
                )}
              </nav>
            </div>

            <div className="grid gap-3">
              <button
                type="button"
                onClick={onToggleTheme}
                className="inline-flex items-center justify-center rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-100"
              >
                Toggle {isDarkMode ? "Light" : "Dark"} Mode
              </button>
              <button
                type="button"
                onClick={handleLogout}
                className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white transition hover:-translate-y-0.5 dark:bg-white dark:text-slate-900"
              >
                <LogOut className="h-4 w-4" />
                Logout
              </button>
            </div>
          </div>
        </aside>

        <div className="grid gap-6 pb-10 pt-4 lg:pt-5">
          <section className="glass-card overflow-hidden">
            <div className="grid gap-6 bg-slate-950 px-6 py-8 text-white md:px-8 lg:grid-cols-[1fr_0.9fr]">
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.26em] text-cyan-300">
                  Dashboard overview
                </p>
                <h1 className="mt-4 font-display text-4xl font-bold">
                  Screen faster, save every report, and keep the next step obvious.
                </h1>
                <p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300">
                  This dashboard is built around a practical flow: upload or capture an eye image,
                  review the AI output, revisit prior scans, and watch stage distribution trends.
                </p>
              </div>

              <div className="grid gap-4 md:grid-cols-3 lg:grid-cols-1 xl:grid-cols-3">
                {quickStats.map((card) => (
                  <div
                    key={card.label}
                    className="rounded-[24px] border border-white/10 bg-white/5 p-5"
                  >
                    <p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-400">
                      {card.label}
                    </p>
                    <p className="mt-3 font-display text-3xl font-bold text-white">{card.value}</p>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {loadingDashboard ? (
            <div className="section-shell grid min-h-[240px] place-items-center">
              <p className="text-sm text-slate-500 dark:text-slate-400">Loading dashboard data...</p>
            </div>
          ) : null}

          <UploadCard loading={analyzing} onAnalyze={handleAnalyze} resetKey={uploadResetKey} />

          <ResultCard
            result={currentResult}
            onSaveReport={handleSaveReport}
            onScanAgain={handleScanAgain}
            userEmail={authUser?.email}
            userName={authUser?.name}
            isDarkMode={isDarkMode}
          />

          <HistoryTable
            reports={reports}
            onView={handleViewReport}
            selectedReportId={currentResult?.report_id}
            activeViewId={activeViewId}
            loading={loadingDashboard}
          />

          <StageChart stats={stats || emptyStats} />
        </div>
      </div>
    </main>
  );
}


export default Dashboard;
