import os
import sys
from functools import lru_cache
from typing import Dict

import cv2
import numpy as np
from PIL import Image


CURRENT_DIR = os.path.abspath(os.path.dirname(__file__))
BACKEND_DIR = os.path.abspath(os.path.join(CURRENT_DIR, os.pardir))

if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from config import Config


ADVICE_MAP = {
    "Normal": "Your eye appears healthy. Continue regular eye check-ups.",
    "Mild": "Early-stage cataract detected. Please consult an ophthalmologist.",
    "Severe": "Advanced cataract detected. Surgical consultation is strongly recommended.",
}


@lru_cache(maxsize=1)
def get_model():
    if not os.path.exists(Config.MODEL_PATH):
        return None
    from tensorflow.keras.models import load_model

    return load_model(Config.MODEL_PATH)


def preprocess_image(img_path: str) -> np.ndarray:
    image = Image.open(img_path).convert("RGB")
    image = image.resize(Config.IMG_SIZE)
    image_array = np.asarray(image, dtype=np.float32) / 255.0
    return np.expand_dims(image_array, axis=0)


def heuristic_probabilities(img_path: str) -> Dict[str, float]:
    grayscale = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if grayscale is None:
        raise ValueError("Unable to read image for fallback analysis.")

    grayscale = cv2.resize(grayscale, Config.IMG_SIZE)
    normalized = grayscale.astype(np.float32) / 255.0

    mean_brightness = float(np.mean(normalized))
    contrast = float(np.std(normalized))
    bright_ratio = float(np.mean(normalized > 0.72))
    haze_score = (
        0.45 * mean_brightness
        + 0.35 * bright_ratio
        + 0.20 * (1.0 - min(contrast / 0.35, 1.0))
    )

    centers = np.array([0.22, 0.52, 0.80], dtype=np.float32)
    distances = np.abs(centers - haze_score)
    logits = np.exp(-6.5 * distances)
    probabilities = logits / np.sum(logits)

    return {
        class_name: round(float(score) * 100, 2)
        for class_name, score in zip(Config.CLASSES, probabilities)
    }


def predict(img_path: str) -> Dict[str, object]:
    model = get_model()
    if model is None:
        probabilities = heuristic_probabilities(img_path)
        predicted_stage = max(probabilities, key=probabilities.get)
        confidence = round(float(probabilities[predicted_stage]), 2)

        return {
            "stage": predicted_stage,
            "confidence": confidence,
            "probabilities": probabilities,
            "advice": (
                f"{ADVICE_MAP[predicted_stage]} "
                "Fallback demo analysis was used because the trained model file is not available yet."
            ),
            "analysis_mode": "heuristic_demo",
            "model_message": (
                "Demo mode is active. Run `python model/train.py` in the backend folder "
                "to switch to the trained CNN model."
            ),
        }

    processed_image = preprocess_image(img_path)
    predictions = model.predict(processed_image, verbose=0)[0]

    probabilities = {
        class_name: round(float(score) * 100, 2)
        for class_name, score in zip(Config.CLASSES, predictions)
    }

    predicted_index = int(np.argmax(predictions))
    predicted_stage = Config.CLASSES[predicted_index]
    confidence = round(float(predictions[predicted_index]) * 100, 2)

    return {
        "stage": predicted_stage,
        "confidence": confidence,
        "probabilities": probabilities,
        "advice": ADVICE_MAP[predicted_stage],
        "analysis_mode": "trained_model",
        "model_message": "Prediction generated by the trained CNN model.",
    }


if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit("Usage: python model/predict.py <image_path>")

    image_path = sys.argv[1]
    print(predict(image_path))
